LinearTrend:
  alpha: loguniform(0.001, 10)
  trend_order: quniform(1, 4, 1)
Linear:
  alpha: loguniform(0.001, 10)
  cyclic_feature_encoding:
    - sincos
    - onehot 
Prophet:
  growth:
    - linear
    - logistic
  seasonality_mode:
    - additive
    - multiplicative 
  cyclic_feature_encoding:
    - sincos
    - onehot 
  n_changepoints: quniform(5, 50, 1)
  changepoint_range: uniform(0.5, 0.4) 
  seasonality_prior_scale: loguniform(0.01, 10) 
  changepoint_prior_scale: loguniform(0.01, 10)
LGB:
  learning_rate: loguniform(0.01, 0.99)
  max_depth: quniform(1, 10, 1)
  min_child_weight: quniform(1, 10, 1)
  boosting: 
    - gbdt
    - dart
  min_gain_to_split: uniform(0, 10)
  num_leaves: quniform(10, 300, 10) 
  subsample: uniform(0.5, 0.4)
  colsample_bytree: uniform(0.5, 0.4) 
  colsample_bynode: uniform(0.5, 0.4)
  reg_lambda: uniform(0, 1)
  reg_alpha: quniform(0, 100, 1)
  cyclic_feature_encoding:
    - sincos
    - onehot
XGB:
  learning_rate: loguniform(0.01, 0.99)
  max_depth: quniform(1, 10, 1)
  min_child_weight: quniform(1, 10, 1)
  booster:
    - gbtree
    - dart
  min_split_loss: uniform(0, 10)
  subsample: uniform(0.5, 0.4)
  colsample_bytree: uniform(0.5, 0.4)
  colsample_bylevel: uniform(0.5, 0.4) 
  colsample_bynode: uniform(0.5, 0.4) 
  reg_lambda: uniform(0, 1)
  reg_alpha: quniform(0, 100, 1)
  cyclic_feature_encoding:
    - sincos
    - onehot
Sarimax:
  p: quniform(0, 10, 1)
  d: quniform(0, 10, 1)
  q: quniform(0, 10, 1)
  seasonal_p: quniform(0, 10, 1)
  seasonal_d: quniform(0, 10, 1)
  seasonal_q: quniform(0, 10, 1)
  cyclic_feature_encoding:
    - sincos
    - onehot
LSTM:
  lr: uniform(0.001, 0.01)
  batch_size: 
    - 64
    - 128
    - 256
  lstm_units: quniform(50, 200, 10)
  lstm_layers: quniform(1, 4, 1)
  dense_units: quniform(50, 200, 10)
  dense_layers: quniform(1, 4, 1)
  cyclic_feature_encoding:
    - sincos
    - onehot
  type:
    - vanilla
    - encoder-decoder
  stateful:
    - True
    - False
  factor: uniform(0.5, 0.9)